### ISSUE TITLE
saving workflows with localhost

### ISSUE THREAD

**Issue by AnirudhG07** [workfloows/workfloows-tutorials#2]
Hi! Thanks for the awesome GitHub workflow you made.
I followed the steps you have given but I am stuck at one step which is the n8n credentials node.
It gives me this error.

<img width="884" alt="image" src="https://github.com/user-attachments/assets/cf6fb7ba-4ae6-453d-92b4-795cc5f46785" />

## How I setup n8n
I am using Docker to setup my n8n instance, hosted locally. It is the same Dockerfile present [here](https://github.com/drudge/n8n-nodes-puppeteer/tree/main/docker).

Now wherever you have used `https://your_website.com` I have put `http://localhost/port_number`

## Whats working
The Github credential node is working just fine and I am getting the files present in my repo too. The other nodes I coudnt test after the n8n credential node since that didnt work.

Please share how I can setup connection via GitHub using localhost?

**Comment by workfloows** [comment]
Hey, thank you for reporting the issue. 

The problem here is not functionality of workflow itself, but the method of installation of n8n. In case of Docker, you need to use gateway IP to access the API of n8n. You can do it by entering command `docker network inspect bridge`. In my case IP is `172.17.0.1`.

<img width="396" alt="Zrzut ekranu 2024-12-19 o 14 27 08" src="https://github.com/user-attachments/assets/058a8149-91c3-42e0-a1a4-a4f0105e9a7e" />

Use this IP together with the port to access the n8n API. 

<img width="843" alt="Zrzut ekranu 2024-12-19 o 14 28 28" src="https://github.com/user-attachments/assets/974c8f48-5568-4b70-9e59-9547282f40d4" />

Remember that gateway IPs can change e.g. after Docker restart or re-configuration. 

Hope it helps!

**Comment by AnirudhG07** [comment]
Will 127.0.0.1 work? I dont think that would change

**Comment by AnirudhG07** [comment]
Thanks, the 127.0.0.1 worked actually!!!
